exports.responses = {
  SERVER_ERROR: "Server error",
  USER_FOUND: "User found successfully",
  USERS_FOUND: "Users found successfully",
  INVALID_CREDENTIALS: "Invalid credentials",
  USER_NOT_FOUND: "User not found",
  USER_CREATED: "User created successfully",
  USER_FAILED: "User creation failed",
  USER_BANNED_BY_ADMIN: "User is banned by admin",
  CATEGORY_FETCHED: "Category fetched successfully",
  CATEGORY_CREATED: "Category created successfully",
  CATEGORY_UPDATED: "Category updated successfully",
  POST_CREATED: "Post submitted successfully",
  POSTS_FOUND: "Post fetched successfully",
  POST_UPDATED: "Post updated successfully",
  POST_DELETED: "Post deleted successfully",
  COMMENT_CREATED: "Comment created successfully",
  COMMENT_DELETED: "Comment deleted successfully",
  POST_LIKED: "Post liked successfully",
  POST_UNLIKED: "Post unliked successfully",
};
